server:
  port: 8174
  tomcat:
    threads:
      max: 1000 #设置 Tomcat 最大线程数（表示 Tomcat 处理请求的线程池大小，即为 Tomcat 的并发处理能力）
    accept-count: 200 #设置 Tomcat 最大连接数（表示等待 Tomcat 线程处理的请求队列大小）
spring:
#Mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zf?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&&failOverReadOnly=false
    username: root
    password: root
#持久层 mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false #禁用缓存
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.zcl.auth.*.model #实体对象扫描，减少xml编写

#日志
logging:
  level:
    com.zcl.anth.feign.log.client.LogFeignClient: debug


